{% set version = "5.47.0" %}
{% set name = "maxima" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://sourceforge.net/projects/maxima/files/Maxima-source/{{ version }}-source/{{ name }}-{{ version }}.tar.gz
  sha256: 9104021b24fd53e8c03a983509cb42e937a925e8c0c85c335d7709a14fd40f7a
  patches:
    # Patches from https://git.sagemath.org/sage.git/tree/build/pkgs/maxima/patches
    # Fixes a test failure that can occur when the install tree has been
    # relocated; see https://trac.sagemath.org/ticket/11348
    - patches/infodir.patch
    # Fixes a bug in matrix inversion that affects Sage; see
    # https://sourceforge.net/p/maxima/bugs/2596/
    - patches/matrixexp.patch
    # Disables a few tests that currently do not pass, see #14
    - patches/osx_tests.patch
    # Disable test that fails with ecl 16.1.2 in some setups
    - patches/rtest8.patch
    # Disable tests that started fails in 5.42.2
    - patches/disable_5_42_2_tests.diff

build:
  number: 2
  skip: true  # [win or (osx and arm64)]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - libtool
    - texinfo
    - make
    - ecl   # [build_platform != target_platform]
  host:
    - ecl
    - readline
    - gmp
  run:
    - readline
    - {{ pin_compatible('ecl', max_pin='x.x.x') }}
    - gmp
  run_constrained:
    # sagelib <10.1 is incompatible with maxima 5.47, see https://github.com/conda-forge/maxima-feedstock/issues/33
    - sagelib >=10.1

test:
  files:
    - run-from-ecl.lisp
  commands:
    - maxima --version
    - ecl -shell run-from-ecl.lisp

about:
  home: http://maxima.sourceforge.net/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Maxima is a system for the manipulation of symbolic and numerical expressions.
  doc_url: http://maxima.sourceforge.net/documentation.html
  dev_url: https://sourceforge.net/p/maxima/code/ci/master/tree/

extra:
  recipe-maintainers:
    - embray
    - isuruf
    - saraedum
