{% set version = "5.42.1" %}
{% set name = "maxima" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://sourceforge.net/projects/maxima/files/Maxima-source/{{ version }}-source/{{ name }}-{{ version }}.tar.gz
  sha256: 8f555aec33bc61b5a3ee0fe2e9d6c1179db67a2ff7e0eceb6bb614058eeb40cd
  patches:
    # Patches from https://git.sagemath.org/sage.git/tree/build/pkgs/maxima/patches
    # Fixes an overflow of the lisp stack when expanding some Taylor series;
    # see https://sourceforge.net/p/maxima/bugs/2520/
    - patches/0001-taylor2-Avoid-blowing-the-stack-when-diff-expand-isn.patch
    # Fixes a test failure that can occur when the install tree has been
    # relocated; see https://trac.sagemath.org/ticket/11348
    - patches/infodir.patch
    # Fixes a bug in matrix inversion that affects Sage; see
    # https://sourceforge.net/p/maxima/bugs/2596/
    - patches/matrixexp.patch
    # Fixes a regression in printing that causes test failures in Sage, and
    # has not been reverted yet; see https://trac.sagemath.org/ticket/13364#comment:89
    - patches/undoing_true_false_printing_patch.patch
    # Disables a few tests that currently do not pass on OSX, at least under
    # Travis, for unknown reasons
    - patches/osx_tests.patch  # [osx]
    # Build a fasl library for ecl
    - patches/maxima.system.patch
    # Disable test that fails with ecl 16.1.2 in some setups
    - patches/rtest8.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - texinfo
  host:
    - ecl 16.1.2
    - readline
    - gmp
    - bdw-gc
  run:
    - readline
    - {{ pin_compatible('ecl', max_pin='x.x.x') }}
    - gmp
    - {{ pin_compatible('bdw-gc') }}

test:
  files:
    - run-from-ecl.lisp
  commands:
    - maxima --version
    - ecl -shell run-from-ecl.lisp

about:
  home: http://maxima.sourceforge.net/
  license: GPLv2+
  license_file: COPYING
  summary: Maxima is a system for the manipulation of symbolic and numerical expressions.
  doc_url: http://maxima.sourceforge.net/documentation.html
  dev_url: https://sourceforge.net/p/maxima/code/ci/master/tree/

extra:
  recipe-maintainers:
    - embray
    - isuruf
    - saraedum
